CREATE PROCEDURE [dbo].[Auth_AddRole]
	@id UNIQUEIDENTIFIER,
	@name VARCHAR(64)
AS
	SET XACT_ABORT ON;
	BEGIN TRANSACTION;

	INSERT INTO Auth_PermissionOwner VALUES(@id, 2);
	INSERT INTO Auth_Role VALUES(@id, 2, @name);

	COMMIT TRANSACTION;
RETURN 0;