//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R.Server.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R.Server.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled task &apos;{0}&apos; has completed successfully at {1:HH:mm dd.MM.yyyy}.
        /// </summary>
        internal static string ScheduledTaskCompletedMessageTemplate {
            get {
                return ResourceManager.GetString("ScheduledTaskCompletedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled task &apos;{0}&apos; failed. Reason: &apos;{1}&apos;..
        /// </summary>
        internal static string ScheduledTaskFailedMessageTemplate {
            get {
                return ResourceManager.GetString("ScheduledTaskFailedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task with the name &apos;{0}&apos; exists in registered task list.
        /// </summary>
        internal static string ScheduledTaskNotExists {
            get {
                return ResourceManager.GetString("ScheduledTaskNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled task &apos;{0}&apos; has been started successfully.
        /// </summary>
        internal static string ScheduledTaskStartedMessageTemplate {
            get {
                return ResourceManager.GetString("ScheduledTaskStartedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find scheduler config!.
        /// </summary>
        internal static string SchedulerConfigNotFound {
            get {
                return ResourceManager.GetString("SchedulerConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in &apos;{0}&apos; has occured with message {1}.
        /// </summary>
        internal static string SchedulerHostExceptionWarningTemplate {
            get {
                return ResourceManager.GetString("SchedulerHostExceptionWarningTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks found to schedule! Stopping scheduler host.
        /// </summary>
        internal static string SchedulerHostNoTasksFoundMessage {
            get {
                return ResourceManager.GetString("SchedulerHostNoTasksFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler service started successfully.
        /// </summary>
        internal static string SchedulerStartedMessage {
            get {
                return ResourceManager.GetString("SchedulerStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler service starting with {0} supplied jobs.
        /// </summary>
        internal static string SchedulerStartingMessageTemplate {
            get {
                return ResourceManager.GetString("SchedulerStartingMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler service has been successfully stopped.
        /// </summary>
        internal static string SchedulerStoppedMessage {
            get {
                return ResourceManager.GetString("SchedulerStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to stop the scheduler service .
        /// </summary>
        internal static string SchedulerStoppingMessage {
            get {
                return ResourceManager.GetString("SchedulerStoppingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong cron entry for the scheduled task &apos;{0}&apos;! This task will never be executed!.
        /// </summary>
        internal static string WrongCronEntryMessageTemplate {
            get {
                return ResourceManager.GetString("WrongCronEntryMessageTemplate", resourceCulture);
            }
        }
    }
}
