CREATE PROCEDURE Auth_AddPrincipal
	@id UNIQUEIDENTIFIER
AS
	SET XACT_ABORT ON;
	BEGIN TRANSACTION;

	INSERT INTO Auth_PermissionOwner VALUES(@id, 1);
	INSERT INTO Auth_Principal VALUES(@id);

	COMMIT TRANSACTION;
RETURN 0;